name: minecraft-stats-viewer

services:
  backend:
    build: ./server
    image: jvicente/mc-stats-api:latest
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - SERVER_JAR=${SERVER_JAR}
      - CLIENT_JAR=${CLIENT_JAR}

      - ORIGIN_DATA=/mcroot
      - ORIGIN_WORLD=/world
      - LOCAL_DATA=/data
      - ASSETS_DIR=/assets
      - RCON_HOST=mc
      - RCON_PORT=${RCON_PORT}
      - RCON_PASSWORD=${RCON_PASSWORD}
      - RCON_TIMEOUT_MS=${RCON_TIMEOUT_MS}
    networks:
      - default
      - vanilla_default
  
  networks:
    vanilla_default:
      external: true
      
    volumes:
      - ${ORIGIN_DATA}:/mcroot:ro
      - ${ORIGIN_WORLD}:/world:ro
      - ${LOCAL_DATA}:/data:ro
      - ${ASSETS_DIR}:/assets:ro

    ports:
      - "${PORT}:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    profiles: [prod]

  client:
    build: 
      context: ./client
    image: jvicente/mc-stats-client:latest
    ports:
      - "${CLIENT_PORT}:80"
    restart: unless-stopped
    profiles: [prod]

  cloudflared:
    image: cloudflare/cloudflared:2025.8.1
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on: [backend, client]
    restart: unless-stopped
    profiles: ["prod"]